#ifndef __TOKENKIND_H__
#define __TOKENKIND_H__

namespace SmileLibInterop {
	public enum class TokenKind {
		ERROR = -2,
		NONE = -1,

		EOI = 0,

		WHITESPACE,
		WHITESPACE_BOM,
		NEWLINE,
		COMMENT_SINGLELINE,
		COMMENT_MULTILINE,
		COMMENT_SEPARATOR_EQUALS,
		COMMENT_SEPARATOR_HYPHEN,
		COMMENT_HASHBANG,

		ALPHANAME,
		PUNCTNAME,

		CHAR,
		UNI,
		BYTE,
		INTEGER16,
		INTEGER32,
		INTEGER64,
		INTEGER128,
		REAL32,
		REAL64,
		REAL128,
		FLOAT32,
		FLOAT64,
		FLOAT128,

		RAWSTRING,
		LONGRAWSTRING,
		DYNSTRING,
		LONGDYNSTRING,

		LEFTBRACE,
		RIGHTBRACE,
		LEFTPARENTHESIS,
		RIGHTPARENTHESIS,
		LEFTBRACKET,
		RIGHTBRACKET,

		BAR,
		EQUAL,
		EQUALWITHOUTWHITESPACE,
		BACKTICK,
		DOUBLEHASH,
		DOT,
		DOTDOT,
		DOTDOTDOT,
		COLON,
		COMMA,
		SEMICOLON,
		AT,
		ATAT,

		// Loanwords.
		LOANWORD__FIRST,
		LOANWORD_INCLUDE,
		LOANWORD_REGEX,
		LOANWORD_XML,
		LOANWORD_JSON,
		LOANWORD_BRK,
		LOANWORD_SYNTAX,
		LOANWORD_LOANWORD,
		LOANWORD_CUSTOM,
		LOANWORD__LAST,

		// These kinds are required by the parser, but are not directly returned by the lexer.
		KNOWNNAME,
		UNKNOWNALPHANAME,
		UNKNOWNPUNCTNAME,
	};
}

#endif